export const GET_CURRENCIES = "GET_CURRENCIES";
export const GET_CURRENCIES_START = "GET_CURRENCIES_START";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAIL = "GET_CURRENCIES_FAIL";

export const GET_CURRENCY = "GET_CURRENCY";
export const GET_CURRENCY_START = "GET_CURRENCY_START";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAIL = "GET_CURRENCY_FAIL";
